---
title: ""
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    latex_engine: xelatex
    includes:
      before_body: cover.tex

header-includes:
  - \usepackage{xcolor}
---


\newpage

# Introduction

Ce document présente le prétraitement appliqué à des données  de l'Enquête Harmonisée sur les Conditions de Vie des Ménages (EHCVM) 2018 au Sénégal pour mener à bien l'ensemble des analyses nécessaires dans le cadre du projet portant sur l'évaluation de l'impact des transferts sur le bien-être des ménages.


# Objectifs

Tout au long de ce projet, il sera question de : 

- Analyser la structure des revenus des ménages (hors bénéfices de l'agriculture et de l'élevage).
- Évaluer l'importance des transferts dans le revenu total des ménages (hors bénéfices de l'agriculture et de l'élevage).
- Mesurer l'impact des transferts sur :  
  - l'éducation dans les ménages,  
  - les dépenses de santé,  
  - les revenus en cas de mauvais rendements.


# Traitement des données


##  Données éducatives


L'objectif de cette partie est qu'en se servant de la base s02_me_sen2018, qu'on détermine le nombre d'individus et le nombre de personnes ayant suivi une formation ou une école (formelle ou non formelle).


Lorsqu'il y a eu une valeur manquante, on l'a imputé par la classe majoritaire du ménage. Lorsqu'il y a eu un ménage où il y a des valeurs manquants pour les variables qui nous ont été nécessaires pour chaque individu, on l'a exclu pour la suite de nos analyses.


A la fin de cette partie, nous avons obtenu une nouvelle base de données "data_menage.dta" contenant les variables :

- grappe et menage (les identifiants des ménages retenus),

- nb_individus (le nombre d'individus par ménage),

- nb_individus_etudes (le nombre d'individus ayant suivi une formation ou une école par ménage).

Tous les scripts R utilisés pour cette opération sont contenus dans le fichier :

- "Exposé EHCVM_s02_me_sen2018_Education.R".


##  Données sur les dépenses de santé


L'objectif est qu'en se servant de la base s03_me_sen2018, qu'on évalue les dépenses de santé au cours des 12 derniers mois pour chaque ménage.

Nous avons évaluer les dépenses de santé au cours des 12 derniers mois pour chaque individu, avant d'agréger par ménage.

Lorsqu'on a rencontré des dépenses de santé effectuées au cours des 03 derniers mois, on les a multipliées par 04 pour avoir une estimation desdites depenses au cours des 12 derniers mois.

Lorsqu'on a rencontré un individu couvert par une assurance maladie, nous avons déduit le montant remboursé de ces dépenses.

A la fin de cette partie, nous avons obtenu une nouvelle base de données "depenses_menage.dta" contenant les variables :

- grappe et menage (les identifiants des ménages retenus),

- depenses_menage (le montant des dépenses en santé de chaque ménage au cours des 12 derniers mois, en tenant de l'assurance).

Tous les scripts R utilisés pour cette opération sont contenus dans le fichier :

- "Exposé EHCVM_s03_me_sen2018_General Health.R".



## Revenus issus et non issus de l'emploi (pension retraite, pension de veuvage, pension alimentaire, etc.)


L'objectif est qu'en se servant des bases s04_me_sen2018 et s04_me_sen2018, qu'on évalue les revenus issus de l'emploi et non issus de l'emploi pour chaque ménage.

Pour y arriver, nous avons d'abord déterminer les revenus issus de l'emploi par an pour chaque individu. Ainsi, pour des revenus hebdomadaires, mensuelles, trimestrielles et semestrielles, nous les avons convertis en des revenus annuelles. Nous en avons fait de même avec les revenus non issus de l'emploi, avant de tous les agréger au niveau ménage.

A la fin de cette partie, nous avons obtenu un nouveau dataframe "revenu_annuel_menage" contenant les variables :
- vague, grappe et menage (les identifiants des ménages),

- revenu_emploi_total,

- revenu_non_emploi_total.

Tous les scripts R utilisés pour cette opération sont contenus dans les fichiers : 

- "Exposé EHCVM_s04_me_SEN2018_Revenu issu de l'emploi.R",

- "Exposé EHCVM_s05_me_SEN2018_Revenu non issu de l'emploi.R".



##  Données sur les Transferts reçus par les ménages


L'objectif est qu'en se servant de la base Exposé s13a_2_me_sen2018, qu'on évalue le montant global des transferts reçus au cours des 12 derniers moi par chaque ménage.

Pour y arriver, nous avons d'abord déterminer le montant des transferts reçus par an pour chaque individu. Ainsi, pour des transferts hebdomadaires, mensuels, trimestriels et semestriels, nous les avons convertis en des transferts annuels. 

A la fin de cette partie, nous avons intégré dans le dataframe "revenu_annuel_menage", les variables :

- transfert_total_menage (la somme des transferts reçus au cours des 12 derniers mois par chaque ménage),

- part_transferts_revenu_total (la part des transferts dans le revenu total, comprenant uniquement les transferts, les revenus issus et non issus de l'emploi).

Celui-ci a été enregistré dans le fichier "revenu_12_derniers_mois_menage_EHCVM.dta".

Tous les scripts R utilisés pour cette opération sont contenus dans le fichier :

- "Exposé EHCVM_s13a_2_me_sen2018_Transferts reçus par les ménages.R".


##   Fusion des bases et finalisation


Les trois bases principales (*revenu_12_derniers_mois_menage_EHCVM.dta*, *depenses_menage.dta*, *data_menage.dta*) ont été fusionnées sur les identifiants communs.

Ensuite, une variable supplémentaire a été créée :  
- ratio_etude (le pourcentage de personnes scolarisées dans chaque ménage).

La base finale *data_menage_final* comporte 6273 ménages et les variables suivantes :  
- vague, grappe, ménage,  
- nb_individus, nb_individus_etudes,  
- dépenses_menage,  
- revenu_emploi_total, revenu_non_emploi_total,  
- transfert_total_menage, part_transferts_revenu_total,  
- ratio_etude.

  
    
Tous les scripts R utilisés pour cette opération sont contenus dans le fichier :

- "Exposé EHCVM_Analyse.R".  
  
   
   
# Conclusion

Ce prétraitement constitue le socle de nos analyses ultérieures sur l'impact des transferts dans les ménages sénégalais.


